# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

PackageIdentifier: LingitAS.Lingdys4
PackageVersion: 4.5.111.0
PackageLocale: nb-NO
Publisher: Lingit AS
PublisherUrl: https://lingit.no/
PublisherSupportUrl: https://lingit.no/kontakt/
PrivacyUrl: https://lingit.no/personvern/personvernerklaering/
Author: LingIT
PackageName: Lingdys 4
PackageUrl: https://download2.lingit.no/update/LingX4/Lingdys_4-Installer.msi
License: Proprietary
LicenseUrl: https://lingit.no/personvern/bruksbetingelser/
Copyright: LingIT AS, 2001-2022
CopyrightUrl: https://lingit.no/personvern/bruksbetingelser/
ShortDescription: LingDys 4 - Hjelp til å lese, skrive og forstå
Description: LingDys 4 - Gir hjelp i lese- og skriveopplæringen, dekker ulike behov, bidrar til økt digital kompetanse.
Moniker: LingDys
Tags:
- LingDys
ReleaseNotes: Lingdys 4.5.111
--== NY / FORBEDRET FUNKSJONALITET ==--
* Skriverammer er implementert som et nytt menyvalg.

--== FEILRETTINGER ==--
* Rettet feil som førte til at "Skann matte" ikke fungerte i automatisk oppdaterte versjoner av Lingdys.
* Rettet feil som førte til at flere brukerord enn de markert for sletting ble slettet.
* Rettet feil som førte til at man i Editor ikke fikk ordfullføring, hvis innstillingen "Etter mellomrom vis: Stavekontroll" var valgt.
* Rettet feil som førte til at det bare var mulig å endre lesehastigheten ett nivå opp eller ned, før menyen lukket seg.
* Rettet feil som førte til at forslagsvinduet dekket over teksten som ble skrevet i Notisblokk i Windows 11. 
* Rettet feil som førte til at markeringen av feilstavede ord i dokumentet forsvant etter man enten satte inn et korrekt ord eller trykket "Overse" i Word skrivebordsversjon i Windows 11.
* Rettet feil som førte til at man fikk et sort felt under verktøylinjen hvis man byttet fra festet verktøylinje til flytende verktøylinje.
ReleaseNotesUrl: https://download.lingit.no/Manualer/Lingdys_Pluss-Windows-Brukerveiledning.pdf
PurchaseUrl: https://lingit.no/butikk/
ManifestType: defaultLocale
ManifestVersion: 1.2.0
